# http://docs.ros.org/en/noetic/api/robot_localization/html/state_estimation_nodes.html

# base parameters

frequency: 10
sensor_timeout: 0.1
two_d_mode: true

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
base_link_frame_output: base_footprint
world_frame: map # "map_frame" if use GPS; "odom_frame" if not use GPS

publish_tf: false # "world_frame" -> "base_link_frame"
publish_acceleration: false
permit_corrected_publication: false
print_diagnostics: false

transform_time_offset: 0.0
transform_timeout: 0.0

initial_state: [0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0]

# rgbd odometry
odom0: /rtabmap/visual_odometry
odom0_config:  [false, false, false,
                false, false, true,
                false, true, false,
                false, false, false,
                false, false, false]
odom0_queue_size: 5
odom0_differential: false
odom0_relative: false
odom0_nodelay: false

# Wheel odometry (20 Hz)
odom1: /tigra/wheel_odom
odom1_config:  [false, false, false,
                false, false, false,
                true, false, false,
                false, false, false,
                false, false, false]
odom1_queue_size: 5
odom1_differential: false
odom1_relative: false
odom1_nodelay: false

# IMU in RealSense D435i (20 Hz)
imu0: /rear_rs_d435i_camera/imu
imu0_config: [false, false, false,
              false, false, true,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_queue_size: 5
imu0_differential: false
imu0_relative: false
imu0_nodelay: false
imu0_remove_gravitational_acceleration: true

# gps
odom2: /odometry/gps # (1 Hz)
odom2_config:  [true, true, false,
                false, false, false,
                false, false, false,
                false, false, false,
                false, false, false]
odom2_queue_size: 5
odom2_differential: false
odom2_relative: false
odom2_nodelay: false

# advanced parameters

use_control: false
stamped_control: false
control_timeout: 1.0
control_config:  [true, true, false,
                  false, false, true]

acceleration_limits: [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]
acceleration_gains:  [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]
deceleration_gains:  [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]

smooth_lagged_data: false
history_length: 0.0
debug: false
debug_out_file: ekf_global.txt

# Q - ковариационная матрица шума процесса - дисперсия переменных состояния
process_noise_covariance:  [0.0025, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0.0025, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0.05,0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0.01,0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004,0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004,0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

dynamic_process_noise_covariance: true

# P - начальное значение ковариационной матрицы оценки состояния (дисперсии переменных)
# рекомендуется ставить значения немного больше чем дисперсий переменных
initial_estimate_covariance: [0.004, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0.004, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0.015, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0.07, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0.015, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.006, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.006, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

reset_on_time_jump: false
predict_to_current_time: true
disabled_at_startup: false
