# base parameters

frequency: 30
sensor_timeout: 0.1
two_d_mode: true

map_frame: map
odom_frame: odom
base_link_frame: base_footprint
base_link_frame_output: base_footprint
world_frame: odom # "map_frame" if use GPS; "odom_frame" if not use GPS

publish_tf: false # "world_frame" -> child_frame
publish_acceleration: false
permit_corrected_publication: false
print_diagnostics: false

transform_time_offset: 0.0
transform_timeout: 0.0

initial_state: [0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0,
                0.0, 0.0, 0.0]

# rgbd odometry (~30 Hz)
odom0: /rtabmap/visual_odometry
odom0_config:  [true, true, false,
                false, false, true,
                false, true, false,
                false, false, false,
                false, false, false]
odom0_queue_size: 10
odom0_differential: false
odom0_relative: false
odom0_nodelay: true

# Wheel odometry (20 Hz)
odom1: /tigra/wheel_odom
odom1_config:  [false, false, false,
                false, false, false,
                true, false, false,
                false, false, false,
                false, false, false]
odom1_queue_size: 10
odom1_differential: false
odom1_relative: false
odom1_nodelay: true

# IMU in RealSense D435i (20 Hz)
imu0: /front_rs_d455_camera/imu
imu0_config: [false, false, false,
              false, false, false,
              false, false, false,
              false, false, true,
              true, false, false]
imu0_queue_size: 10
imu0_differential: false
imu0_relative: false
imu0_nodelay: false
imu0_remove_gravitational_acceleration: true

# advanced parameters

use_control: false
stamped_control: false
control_timeout: 1.0
control_config:  [true, true, false,
                  false, false, true]

acceleration_limits: [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]
acceleration_gains:  [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]
deceleration_gains:  [0.0, 0.0, 0.0,
                      0.0, 0.0, 0.0]

smooth_lagged_data: false
history_length: 0.0
debug: false
debug_out_file: ekf_global.txt

process_noise_covariance:  [0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (x)
                            0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (y)
                            0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0.01, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (yaw)
                            0, 0, 0, 0, 0, 0, 0.05,0, 0, 0, 0, 0, 0, 0, 0, # /tigra/wheel_odom (v_x)
                            0, 0, 0, 0, 0, 0, 0, 0.01,0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (v_y)
                            0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004,0, 0, 0, # /front_rs_d455_camera/imu (v_yaw)
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.004,0, 0, # /front_rs_d455_camera/imu (a_x)
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-3]

dynamic_process_noise_covariance: true

initial_estimate_covariance: [0.015, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (x)
                              0, 0.015, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (y)
                              0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0.015, 0, 0, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (yaw)
                              0, 0, 0, 0, 0, 0, 0.07, 0, 0, 0, 0, 0, 0, 0, 0, # /tigra/wheel_odom (v_x)
                              0, 0, 0, 0, 0, 0, 0, 0.015, 0, 0, 0, 0, 0, 0, 0, # /rtabmap/visual_odometry (v_y)
                              0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0, 0, 0, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.006, 0, 0, 0, # /rs_camera/imu (v_yaw)
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.006, 0, 0, # /rs_camera/imu (a_x)
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9, 0,
                              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1e-9]

reset_on_time_jump: false
predict_to_current_time: true
disabled_at_startup: false
