# http://docs.ros.org/en/noetic/api/robot_localization/html/navsat_transform_node.html

frequency: 10
delay: 2

magnetic_declination_radians: 0 # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination
yaw_offset: 0 # imu выдает "0" если его ось Х смотрит на восток

zero_altitude: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
broadcast_utm_transform: true
broadcast_utm_transform_as_parent_frame: true
transform_timeout: 0
