# http://docs.ros.org/en/noetic/api/robot_localization/html/navsat_transform_node.html

frequency: 30
delay: 1

magnetic_declination_radians: 0.261799388 # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination
yaw_offset: 1.570796327 # imu выдает "0" если его ось Х смотрит на восток

zero_altitude: true
publish_filtered_gps: true
use_odometry_yaw: false
wait_for_datum: false
broadcast_utm_transform: false
broadcast_utm_transform_as_parent_frame: true
transform_timeout: 0
