frequency: 10
delay: 0.0

magnetic_declination_radians: 0 # https://www.ngdc.noaa.gov/geomag/calculators/magcalc.shtml#declination
yaw_offset: 0 # imu выдает "0" если его ось Х смотрит на восток

zero_altitude: true
publish_filtered_gps: true
use_odometry_yaw: true
wait_for_datum: false
broadcast_utm_transform: false
broadcast_utm_transform_as_parent_frame: true
transform_timeout: 0
