<?xml version="1.0"?>
<robot name="tigra" xmlns:xacro="http://www.ros.org/wiki/xacro">

	<xacro:include filename="$(find tigra_description)/urdf/params.urdf.xacro" />
	<xacro:include filename="$(find maddrive_urdf_tools)/urdf/macros/wheels.urdf.xacro" />
	<xacro:include filename="$(find maddrive_urdf_tools)/urdf/macros/inertia.urdf.xacro" />
	<xacro:include filename="$(find maddrive_urdf_tools)/urdf/macros/common.urdf.xacro" />

	<!-- BASE FOOTPRINT-->

	<link name="base_footprint">
		<xacro:null_visual/>
		<xacro:null_collision/>
		<xacro:null_inertia/>
	</link>
	<gazebo reference="base_footprint" />

	<!-- BASE LINK -->

	<joint name="base_footprint_2_base_link" type="fixed">
		<parent link="base_footprint" />
		<child link="base_link" />
		<origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
	</joint>

	<link name="base_link">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://tigra_description/meshes/quadro.dae" />
			</geometry>
		</visual>
		<collision name="base_collision">
			<origin xyz="${body_length/2-rear_wheel_2_rear_bumper} 0 ${body_heigth/2}" rpy="0 0 0" />
			<geometry>
				<box size="${body_length} ${body_width} ${body_heigth}" />
			</geometry>
		</collision>
		<xacro:box_inertia
			width="${body_width}"
			length="${body_length}"
			height="${body_heigth}"
			mass="${body_mass}">
			<origin xyz="${body_length/2-rear_wheel_2_rear_bumper} 0 ${body_heigth/2}" rpy="0 0 0" />
		</xacro:box_inertia>
	</link>

	<!-- REAR AXIS LINK -->

	<joint name="base_footprint_2_rear_axis_link" type="fixed">
		<parent link="base_link" />
		<child link="rear_axis_link" />
		<origin xyz="0 0 0" rpy="0 0 0" />
	</joint>

	<link name="rear_axis_link">
		<xacro:null_visual/>
		<xacro:null_collision/>
		<xacro:null_inertia/>
	</link>

	<!-- FRONT AXIS LINK -->

	<joint name="rear_axis_link_2_front_axis_link" type="fixed">
		<parent link="rear_axis_link" />
		<child link="front_axis_link" />
		<origin xyz="${wheelbase} 0 0" rpy="0 0 0" />
	</joint>

	<link name="front_axis_link">
		<xacro:null_visual/>
		<xacro:null_collision/>
		<xacro:null_inertia/>
	</link>

	<!-- WHEELS -->

	<xacro:steer_wheel
		prefix="front_right"
		parent="front_axis_link"
		steer_origin_xyz="0 -${track_width/2} 0"
		steer_limit="${wheel_turn_limit}" />
	<xacro:steer_wheel
		prefix="front_left"
		parent="front_axis_link"
		steer_origin_xyz="0 ${track_width/2} 0"
		steer_limit="${wheel_turn_limit}" />
	<xacro:speed_wheel
		prefix="rear_right"
		parent="rear_axis_link"
		origin_xyz="0 -${track_width/2} 0" />
	<xacro:speed_wheel
		prefix="rear_left"
		parent="rear_axis_link"
		origin_xyz="0 ${track_width/2} 0" />

    <gazebo>
        <plugin name="tigra_interface_plugin" filename="libackermann_raw_controller_plugin.so">
            <!-- <maxSteerRad>${mid_wheel_turn_limit}</maxSteerRad> -->
            <wheelbase>${wheelbase}</wheelbase>
            <!-- <wheelRadius>${wheel_radius}</wheelRadius> -->
            <trackWidth>${track_width}</trackWidth>
            <!-- <odomFrame>${odom_frame}</odomFrame> -->
            <!-- <pubTf>$(arg pub_tf)</pubTf> -->
            <robotName>$(arg robot_name)</robotName>
        </plugin>
    </gazebo>
</robot>
