<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:arg name="robot_name" default="tigra" />

    <xacro:property name="yaml_file" value="$(find tigra_description)/config/props.yaml" />
    <xacro:property name="props" value="${xacro.load_yaml(yaml_file)}" />

    <!-- основные габариты -->
    <xacro:property name="wheelbase" value="${props['wheelbase']}" />
    <xacro:property name="track_width" value="${props['track_width']}" />
    <xacro:property name="front_wheel_2_front_bumper" value="0.3" />
    <xacro:property name="rear_wheel_2_rear_bumper" value="0.3" />
    <xacro:property name="body_length" value="${front_wheel_2_front_bumper+wheelbase+rear_wheel_2_rear_bumper}" />
    <xacro:property name="body_width" value="0.75" />
    <xacro:property name="body_heigth" value="0.6" />
    <xacro:property name="body_mass" value="340" />

    <!-- габариты колес -->
    <xacro:property name="wheel_width" value="0.25" />
    <xacro:property name="wheel_radius" value="${props['wheel_radius']}" />
    <xacro:property name="wheel_mass" value="20" />

    <!-- характеристики подвески -->
    <xacro:property name="steer_limit" value="${pi/4}" />
    <xacro:property name="suspension_height" value="0.0" />

</robot>
