topics:
-
    name: navigation
    topic: nav_vel
    timeout: 0.5
    priority: 100
-
    name: joystick
    topic: joy_vel
    timeout: 0.5
    priority: 10

locks:
-
  name    : pause
  topic   : detectTrafficLightsCmd
  timeout : 0.0
  priority: 110