global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  update_frequency: 1.0
  publish_frequency: 0.5

  transform_tolerance: 1.0
  
  static_map: true
  width: 80.0
  height: 80.0
  origin_x: -20.0
  origin_y: -20.0

  plugins:
    # - {name: static_layer, type: "costmap_2d::StaticLayer"}
    # - {name: laser_obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: depth_obstacle_layer, type: "costmap_2d::VoxelLayer"}
    # - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
