<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="yaml_file" value="$(find tigra_description)/config/props.yaml" />
    <xacro:property name="props" value="${load_yaml(yaml_file)}" />

    <xacro:property name="body_length" value="1.85" />
    <xacro:property name="body_width" value="0.75" />
    <xacro:property name="body_heigth" value="0.6" />
    <xacro:property name="body_mass" value="340" />

    <xacro:property name="wheel_width" value="0.25" />
    <xacro:property name="wheel_radius" value="${props['wheel_radius']}" />
    <xacro:property name="wheel_mass" value="20" />
    <xacro:property name="wheel_turn_limit" value="${pi/4}" />

    <xacro:property name="wheel_shift_pos" value="0.35" />


    <xacro:property name="wheelbase" value="${props['wheelbase']}" />
    <xacro:property name="half_wheelbase" value="${wheelbase/2}" />
    <xacro:property name="track_width" value="${props['track_width']}" />

    <xacro:property name="lidar_location" value="${heigth/2+0.01}" />

    <xacro:property name="odom_frame" value="odom_wheel" />

    <xacro:arg name="pub_tf" default="true" />
    <xacro:arg name="robot_name" default="tigra" />
</robot>
